### ISSUE TITLE
夏学期第三周工作内容

### ISSUE THREAD

**Issue by Shuenhoy** [ZJUEVA/RPG#1]
* 基本组、图像组每人写一份文档描述对现有代码的理解，包括：
  * 对 ECS 的基本理解， ECS 工作流程等，并举例说明
  * 场景管理机制
  * 目前代码结构，总体流程
  * 若有其他请补充
* 继续学 go
* 剧情组沟通一下格式，然后开始写
* 随便看看 RPG Maker，了解一下 RPG 是怎么做的
* xy和满神列一下目前not implemented的函数

**Comment by godspeedcurry** [comment]
ok
